routes/web.php
<?php

use Illuminate\Support\Facades\Route;

//Admin Namespace
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\DataSampahController;
use App\Http\Controllers\GaleriController;
use App\Http\Controllers\PengumumanController;



//Controllers Namespace
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\DataTransaksiController;
use App\Http\Controllers\Admin\ChangePasswordController;
use App\Http\Controllers\Admin\CountController;
use App\Http\Controllers\Admin\GetJadwalController;
use App\Http\Controllers\Admin\PendaftaranNasabahController;
use App\Http\Controllers\JadwalController;
use App\Http\Controllers\TabunganController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Home
Route::get('/', [HomeController::class, 'index']);
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/about', [HomeController::class, 'about'])->name('about');
Route::get('/contact', [HomeController::class, 'contact'])->name('contact');
Route::get('/login', [HomeController::class, 'login'])->name('login');
Route::get('/register', [RegisterController::class, 'register'])->name('register');
Route::post('/register', [RegisterController::class, 'store'])->name('register');


// register nasabah
Route::get('/nasabah-register', [RegisterController::class, 'registerNasabah'])->name('register.nasabah');
Route::post('/nasabah-register', [RegisterController::class, 'storeRegisterNasabah'])->name('register.nasabah.store');

//data_sampah
Route::get('/data_sampah', [DataSampahController::class, 'index'])->name('data_sampah');
Route::get('/data_sampah/{data_sampah:slug}', [DataSampahController::class, 'show'])->name('data_sampah.show');

//galeri
Route::get('/galeri', [GaleriController::class, 'index'])->name('galeri');
Route::get('/galeri{galeri:slug}', [GaleriController::class, 'show'])->name('galeri.show');

//Pengumuman
Route::get('/pengumuman', [PengumumanController::class, 'index'])->name('pengumuman');
Route::get('/pengumuman/{pengumuman:slug}', [PengumumanController::class, 'show'])->name('pengumuman.show');

//data_transaksi
Route::get('/data_transaksi', [DataTransaksiController::class, 'index'])->name('data_transaksi');
Route::get('/data_transaksi/{data_transaksi:slug}', [DataTransaksiController::class, 'show'])->name('data_transaksi.show');

// jadwal
Route::get('/jadwal', [JadwalController::class, 'index'])->name('jadwal.index');
Route::post('/jadwal', [JadwalController::class, 'store'])->name('jadwal.store');

//count
Route::get('/count', [CountController::class, 'countMonth'])->name('count');

// tabungan
Route::get('/tabungan', [TabunganController::class, 'index'])->name('tabungan.index');
Route::get('/tabungan/create', [TabunganController::class, 'create'])->name('tabungan.create');
Route::get('/tabungan/cetak', [TabunganController::class, 'cetakAll'])->name('tabungan.cetakAll');
Route::get('/tabungan/{id}', [TabunganController::class, 'show'])->name('tabungan.show');
Route::get('/tabungan/{id}/cetak', [TabunganController::class, 'cetakById'])->name('tabungan.cetakById');
Route::post('/tabungan/store', [TabunganController::class, 'store'])->name('tabungan.store');

//Admin
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => ['auth']], function () {
    Route::name('admin.')->group(function () {
        Route::group(['namespace' => '\App\Http\Controllers'], function () {
            Route::get('/', [AdminController::class, 'index'])->name('index')->middleware('can:role, "admin","guest"');
            Route::get('/profile', [ProfileController::class, 'index'])->name('profile.index')->middleware('can:role, "admin","guest"');
            Route::get('/change-password', [ChangePasswordController::class, 'index'])->name('change-password.index')->middleware('can:role, "admin","guest"');
        });

        //Resource Controller
        Route::resource('users', 'UsersController')->middleware('can:role, "admin"');
        Route::resource('admin.index', 'CountController')->middleware('can:role, "admin"');
        Route::resource('pengumuman', 'PengumumanController')->middleware('can:role, "admin"');
        Route::resource('data_transaksi', 'DataTransaksiController')->middleware('can:role, "admin"');
        Route::resource('data_sampah', 'DataSampahController')->middleware('can:role, "admin"');
        Route::resource('galeri', 'GaleriController')->middleware('can:role, "admin"');
        Route::resource('kategori-artikel', 'KategoriArtikelController');

        // pendaftaran
        Route::get('/pendaftaran', [PendaftaranNasabahController::class, 'index']);
        Route::put('/pendaftaran/{id}', [PendaftaranNasabahController::class, 'validateUser']);

        // jadwal admin
        Route::get('/jadwal', [GetJadwalController::class, 'index'])->name('jadwal.index');
        Route::get('/jadwal/{id}', [GetJadwalController::class, 'show'])->name('jadwal.show');

        // tabungan
        Route::get('/saldoUser/{id}', [TabunganController::class, 'getSaldoUser']);
        Route::get('/saldouser/{id}/cetak-resi', [TabunganController::class, 'cetak_withdrawn']);
        Route::post('/saldoUser/tarik', [TabunganController::class, 'tarikSaldo']);
    });
});

resources/views/layouts/backend/app.blade.php
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="csrf-token" content="{{ csrf_token() }}" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <title>Bank Sampah - {{ $title ?? '' }}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('templates/backend/AdminLTE-3.0.1') }}/plugins/fontawesome-free/css/all.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('templates/backend/AdminLTE-3.0.1') }}/dist/css/adminlte.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{{ asset('templates/backend/AdminLTE-3.0.1') }}/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
  @stack('css')
</head>

<body class="hold-transition sidebar-mini layout-fixed">
  <div class="wrapper">

    <!-- Navbar -->
    @include('layouts.backend.navbar')
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    @include('layouts.backend.sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
      <!-- Content Header (Page header) -->
      <div class="content-header">
        <div class="container-fluid">
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">{{ $contentTitle ?? '' }}</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <!-- <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v1</li>
            </ol> -->
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
      </div>
      <!-- /.content-header -->

      <!-- Modal -->
      @include('layouts.backend.modal')

      <!-- Main content -->
      <section class="content">
        <div class="container-fluid">
          @yield('content')
        </div><!-- /.container-fluid -->
      </section>
      <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
      <strong>Copyright &copy; {{ date('Y') }} Defan Ilham Ardiansyah.</strong>
      All rights reserved.
  </div>
  </footer>
  @stack('modal')
  </div>
  <!-- ./wrapper -->

  <!-- jQuery -->
  <script src="{{ asset('templates/backend/AdminLTE-3.0.1') }}/plugins/jquery/jquery.min.js"></script>
  <!-- jQuery UI 1.11.4 -->
  <script src="{{ asset('templates/backend/AdminLTE-3.0.1') }}/plugins/jquery-ui/jquery-ui.min.js"></script>
  <!-- chart -->
  <script src="{{ asset('templates/backend/AdminLTE-3.0.1') }}/plugins/chart.js/Chart.min.js"></script>
  <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
  <script>
    $.widget.bridge('uibutton', $.ui.button)
  </script>
  <!-- Bootstrap 4 -->
  <script src="{{ asset('templates/backend/AdminLTE-3.0.1') }}/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- overlayScrollbars -->
  <script src="{{ asset('templates/backend/AdminLTE-3.0.1') }}/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
  <!-- AdminLTE App -->
  <script src="{{ asset('templates/backend/AdminLTE-3.0.1') }}/dist/js/adminlte.js"></script>
  <script src="{{ asset('templates/backend/AdminLTE-3.0.1') }}/plugins/jquery/jquery.min.js"></script>
  <script src="{{ asset('templates/backend/AdminLTE-3.0.1') }}/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="{{ asset('templates/backend/AdminLTE-3.0.1') }}/dist/js/adminlte.min.js?v=3.2.0"></script>
  <script src="{{ asset('templates/backend/AdminLTE-3.0.1') }}/dist/js/demo.js"></script>
  @stack('js')
</body>

</html>

resources/views/layouts/backend/modal.blade.php
<!-- LogoutModal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Yakin Logout ?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <form method="POST" action="{{ route('logout') }}">
        @csrf
        <button type="submit" class="btn btn-danger">Logout</button>
        </form>
      </div>
    </div>
  </div>
</div>

resources/views/layouts/backend/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-fw fa-bars"></i></a>
    </li>
  </ul>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-user"></i>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-header">{{ auth()->user()->email }}</span>
        <div class="dropdown-divider"></div>
        <a href="{{ route('admin.profile.index') }}" class="dropdown-item">
          <i class="fas fa-fw fa-user mr-2"></i> Profile
        </a>
        <div class="dropdown-divider"></div>
        <a href="/" target="_blank" class="dropdown-item">
          <i class="fas fa-fw fa-home mr-2"></i> Website
        </a>
        <div class="dropdown-divider"></div>
        <a href="javascript:void(0)" class="dropdown-item" data-toggle="modal" data-target="#exampleModal">
          <i class="fas fa-fw fa-sign-out-alt mr-2"></i> Logout
        </a>
      </div>
    </li>
  </ul>
</nav>

resources/views/layouts/backend/sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="/" class="brand-link">
    <img src="{{ asset('img/icons/bank_sampah.JPEG') }}" alt="laravel Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
    <span class="brand-text font-weight-light">bank sampah</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="{{ asset('img/icons') }}/codeigniter4.png" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
        <a href="#" class="d-block">{{ auth()->user()->name }}</a>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item">
          <a href="{{ route('admin.index') }}" class="nav-link {{ Request::is('admin') ? 'active' : '' }}">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
              Dashboard
            </p>
          </a>
        </li>
        <li class="nav-header">MANAGE DATA</li>
        @can('role',['admin'])
        <li class="nav-item">
          <a href="{{ route('admin.users.index') }}" class="nav-link {{ Request::segment(2) == 'users' ? 'active' : '' }}">
            <i class="nav-icon fas fa-users"></i>
            <p>
              Users
            </p>
          </a>
        </li>
        @endcan
        @can('role',['admin'])
        <li class="nav-item">
          <a href="{{url('/admin/pendaftaran')}}" class="nav-link {{ request()->is('admin/pendaftaran') ? 'active' : '' }}">
            <i class="nav-icon fas fa-user"></i>
            <p>
              Pendaftaran Nasabah
            </p>
          </a>
        </li>
        @endcan
        @can('role',['admin'])
        <li class="nav-item">
          <a href="{{ route('admin.data_sampah.index') }}" class="nav-link {{ Request::segment(2) == 'data_sampah' ? 'active' : '' }}">
            <i class="nav-icon far fa-image"></i>
            <p>
              Data Sampah
            </p>
          </a>
        </li>
        @endcan
        @can('role',['admin'])
        <li class="nav-item">
          <a href="{{ route('admin.kategori-artikel.index') }}" class="nav-link {{ Request::segment(2) == 'kategori-artikel' ? 'active' : '' }}">
            <i class="nav-icon far fa-circle"></i>
            <p>
              Kategori Artikel
            </p>
          </a>
        </li>
        @endcan
        @can('role',['admin'])
        <li class="nav-item">
          <a href="{{ route('admin.pengumuman.index') }}" class="nav-link {{ Request::segment(2) == 'pengumuman' ? 'active' : '' }}">
            <i class="nav-icon fas fa-info"></i>
            <p>
              Pengumuman
            </p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{{ route('admin.jadwal.index') }}" class="nav-link {{ Request::segment(2) == 'jadwal' ? 'active' : '' }}">
            <i class="nav-icon far fa-image"></i>
            <p>
              Jadwal Penjemputan
              <p>
          </a>
        </li>
        @endcan
        @can('role',['admin'])
        <li class="nav-item">
          <a href="{{ route('admin.data_transaksi.index') }}" class="nav-link {{ Request::segment(2) == 'data_transaksi' ? 'active' : '' }}">
            <i class="nav-icon fas fa-list"></i>
            <p>
              Data Transaksi
            </p>
          </a>
        </li>
        @endcan
        @can('role',['admin'])
        <li class="nav-item">
          <a href="{{ route('admin.galeri.index') }}" class="nav-link {{ Request::segment(2) == 'galeri' ? 'active' : '' }}">
            <i class="nav-icon far fa-image"></i>
            <p>
              Galeri Foto
              <p>
          </a>
        </li>
        @endcan
        @can('role', ['admin', 'guest'])
        <li class="nav-item">
          <a href="{{ route('tabungan.index') }}" class="nav-link {{ Request::segment(2) == 'tabungan.index' ? 'active' : '' }}">
            <i class="nav-icon fas fa-money-bill"></i>
            <p>
              Tabungan Nasabah
            </p>
          </a>
        </li>
        @endcan
        @can('role', ['guest'])
        <li class="nav-item">
          <a href="{{ route('jadwal.index') }}" class="nav-link {{ Request::segment(2) == 'jadwal' ? 'active' : '' }}">
            <i class="nav-icon fas fa-car"></i>
            <p>
              Jadwal
            </p>
          </a>
        </li>
        @endcan

        <li class="nav-header">PENGATURAN</li>
        @can('role',['admin','guest'])
        <li class="nav-item">
          <a href="{{ route('admin.profile.index') }}" class="nav-link {{ Request::is('admin/profile') ? 'active' : '' }}">
            <i class="nav-icon fas fa-id-card"></i>
            <p>
              Profil
            </p>
          </a>
        </li>
        @endcan
        @can('role',['admin','guest'])
        <li class="nav-item">
          <a href="{{ route('admin.change-password.index') }}" class="nav-link {{ Request::is('admin/change-password') ? 'active' : '' }}">
            <i class="nav-icon fas fa-unlock"></i>
            <p>
              Ubah Password
            </p>
          </a>
        </li>
        @endcan
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>