routes/web.php
<?php

use Illuminate\Support\Facades\Route;

//Admin Namespace
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RegisterController;
use App\Http\Controllers\DataSampahController;
use App\Http\Controllers\GaleriController;
use App\Http\Controllers\PengumumanController;



//Controllers Namespace
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\DataTransaksiController;
use App\Http\Controllers\Admin\ChangePasswordController;
use App\Http\Controllers\Admin\CountController;
use App\Http\Controllers\Admin\GetJadwalController;
use App\Http\Controllers\Admin\PendaftaranNasabahController;
use App\Http\Controllers\JadwalController;
use App\Http\Controllers\TabunganController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Home
Route::get('/', [HomeController::class, 'index']);
Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/about', [HomeController::class, 'about'])->name('about');
Route::get('/contact', [HomeController::class, 'contact'])->name('contact');
Route::get('/login', [HomeController::class, 'login'])->name('login');
Route::get('/register', [RegisterController::class, 'register'])->name('register');
Route::post('/register', [RegisterController::class, 'store'])->name('register');


// register nasabah
Route::get('/nasabah-register', [RegisterController::class, 'registerNasabah'])->name('register.nasabah');
Route::post('/nasabah-register', [RegisterController::class, 'storeRegisterNasabah'])->name('register.nasabah.store');

//data_sampah
Route::get('/data_sampah', [DataSampahController::class, 'index'])->name('data_sampah');
Route::get('/data_sampah/{data_sampah:slug}', [DataSampahController::class, 'show'])->name('data_sampah.show');

//galeri
Route::get('/galeri', [GaleriController::class, 'index'])->name('galeri');
Route::get('/galeri{galeri:slug}', [GaleriController::class, 'show'])->name('galeri.show');

//Pengumuman
Route::get('/pengumuman', [PengumumanController::class, 'index'])->name('pengumuman');
Route::get('/pengumuman/{pengumuman:slug}', [PengumumanController::class, 'show'])->name('pengumuman.show');

//data_transaksi
Route::get('/data_transaksi', [DataTransaksiController::class, 'index'])->name('data_transaksi');
Route::get('/data_transaksi/{data_transaksi:slug}', [DataTransaksiController::class, 'show'])->name('data_transaksi.show');

// jadwal
Route::get('/jadwal', [JadwalController::class, 'index'])->name('jadwal.index');
Route::post('/jadwal', [JadwalController::class, 'store'])->name('jadwal.store');

//count
Route::get('/count', [CountController::class, 'countMonth'])->name('count');

// tabungan
Route::get('/tabungan', [TabunganController::class, 'index'])->name('tabungan.index');
Route::get('/tabungan/create', [TabunganController::class, 'create'])->name('tabungan.create');
Route::get('/tabungan/cetak', [TabunganController::class, 'cetakAll'])->name('tabungan.cetakAll');
Route::get('/tabungan/{id}', [TabunganController::class, 'show'])->name('tabungan.show');
Route::get('/tabungan/{id}/cetak', [TabunganController::class, 'cetakById'])->name('tabungan.cetakById');
Route::post('/tabungan/store', [TabunganController::class, 'store'])->name('tabungan.store');

//Admin
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'middleware' => ['auth']], function () {
    Route::name('admin.')->group(function () {
        Route::group(['namespace' => '\App\Http\Controllers'], function () {
            Route::get('/', [AdminController::class, 'index'])->name('index')->middleware('can:role, "admin","guest"');
            Route::get('/profile', [ProfileController::class, 'index'])->name('profile.index')->middleware('can:role, "admin","guest"');
            Route::get('/change-password', [ChangePasswordController::class, 'index'])->name('change-password.index')->middleware('can:role, "admin","guest"');
        });

        //Resource Controller
        Route::resource('users', 'UsersController')->middleware('can:role, "admin"');
        Route::resource('admin.index', 'CountController')->middleware('can:role, "admin"');
        Route::resource('pengumuman', 'PengumumanController')->middleware('can:role, "admin"');
        Route::resource('data_transaksi', 'DataTransaksiController')->middleware('can:role, "admin"');
        Route::resource('data_sampah', 'DataSampahController')->middleware('can:role, "admin"');
        Route::resource('galeri', 'GaleriController')->middleware('can:role, "admin"');
        Route::resource('kategori-artikel', 'KategoriArtikelController');

        // pendaftaran
        Route::get('/pendaftaran', [PendaftaranNasabahController::class, 'index']);
        Route::put('/pendaftaran/{id}', [PendaftaranNasabahController::class, 'validateUser']);

        // jadwal admin
        Route::get('/jadwal', [GetJadwalController::class, 'index'])->name('jadwal.index');
        Route::get('/jadwal/{id}', [GetJadwalController::class, 'show'])->name('jadwal.show');

        // tabungan
        Route::get('/saldoUser/{id}', [TabunganController::class, 'getSaldoUser']);
        Route::get('/saldouser/{id}/cetak-resi', [TabunganController::class, 'cetak_withdrawn']);
        Route::post('/saldoUser/tarik', [TabunganController::class, 'tarikSaldo']);
    });
});

app/Models/data_transaksi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

use App\Models\User;

class data_transaksi extends Model
{
    use HasFactory;

    protected $table = 'data_transaksi';

    protected $fillable = [
    	'petugas','judul','slug','deskripsi','tgl','jam','berat','totalberat','harga','totalharga', 'user_id',
    ]; 

    public function user()
    {
    	return $this->belongsTo(User::class);
    }

    public function AllData()
    {
    	return DB::table('data_transaksi')->get();
    }
    
}

app/Http/Controllers/Admin/DataTransaksiController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use App\Models\data_transaksi;
use Str;

class DataTransaksiController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data_transaksi = data_transaksi::all();
        return view('admin.data_transaksi.index',compact('data_transaksi'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.data_transaksi.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->request->add([
            'tgl' => date('Y-m-d'),
            'slug' => Str::slug($request->deskripsi),
            'user_id' => auth()->user()->id,
        ]);
        data_transaksi::create($request->all());

        return redirect()->route('admin.data_transaksi.index')->with('success','Data berhasil ditambah');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(data_transaksi $data_transaksi)
    {
        return view('admin.data_transaksi.edit',compact('data_transaksi'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, data_transaksi $data_transaksi)
    {
        $request->request->add([
            'tgl' => date('Y-m-d'),
            'slug' => Str::slug($request->deskripsi),
            'user_id' => auth()->user()->id,
        ]);
        $data_transaksi->update($request->all());
           
        return redirect()->route('admin.data_transaksi.index')->with('success','Data berhasil diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(data_transaksi $data_transaksi)
    {   
        $data_transaksi->delete();
        return redirect()->route('admin.data_transaksi.index')->with('success','Data berhasil dihapus');
    }
}

app/Http/Controllers/DataTransaksiController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\data_transaksi;

class DataTransaksiController extends Controller
{
  public function index()
    {
    	$data_transaksi = data_transaksi::with(['user'])->latest()->paginate(4);
    	return view('data_transaksi.index',compact('data_transaksi'));
    }

    public function show(data_transaksi $data_transaksi)
    {
    	return view('data_transaksi.show',compact('data_transaksi'));
    }

}

resources/views/admin/data_transaksi/create.blade.php
@extends('layouts.backend.app',[
    'title' => 'Tambah Data Transaksi',
    'contentTitle' => 'Tambah data_transaksi'
])

@push('css')
<link rel="stylesheet" type="text/css" href="{{ asset('plugins/summernote') }}/summernote-bs4.min.css">
@endpush

@section('content')
<div class="">    
    <div class="card">
        <div class="card-header">
            <a href="{{ route('admin.data_transaksi.index') }}" class="btn btn-success btn-sm">Kembali</a>
        </div>
        <div class="card-body">
        <form method="POST" enctype="multipart/form-data" action="{{ route('admin.data_transaksi.store') }}">
            @csrf
            <div class="form-group">
                <label for="petugas">petugas</label>
                <input required="" type="" name="petugas" id="petugas" placeholder="" class="form-control title"> 
            </div>
            <div class="form-group">
                <label for="judul">Judul</label>
                <input required="" type="" name="judul" id="judul" placeholder="" class="form-control title"> 
            </div>
            
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="tgl">Tanggal</label>
                        <input type="date" name="tgl" id="tgl" class="form-control">
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="jam">jam</label>
                        <input type="time" name="jam" id="jam" class="form-control">
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="berat">berat</label>
                        <input type="weight" name="berat" id="berat" class="form-control">
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="totalberat">total berat</label>
                        <input type="weight" name="totalberat" id="berat" class="form-control">
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="harga">harga</label>
                        <input type="price" name="harga" id="harga" class="form-control">
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="totalharga">total harga</label>
                        <input type="price" name="totalharga" id="totalharga" class="form-control">
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="deskripsi">Deskripsi</label>
                <textarea required="" name="deskripsi" id="deskripsi" class="text-dark form-control summernote"></textarea>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-sm">UPLOAD</button>    
            </div> 
        </div>
        </form>
    </div>
</div>
@stop

@push('js')
<script type="text/javascript" src="{{ asset('plugins/summernote') }}/summernote-bs4.min.js"></script>
<script type="text/javascript">
    $(".summernote").summernote({
        height:500,
        callbacks: {
        // callback for pasting text only (no formatting)
            onPaste: function (e) {
              var bufferText = ((e.originalEvent || e).clipboardData || window.clipboardData).getData('Text');
              e.preventDefault();
              bufferText = bufferText.replace(/\r?\n/g, '<br>');
              document.execCommand('insertHtml', false, bufferText);
            }
        }
    })

    $(".summernote").on("summernote.enter", function(we, e) {
        $(this).summernote("pasteHTML", "<br><br>");
        e.preventDefault();
    });
</script>
@endpush

resources/views/admin/data_transaksi/edit.blade.php
@extends('layouts.backend.app',[
    'title' => 'Edit Data Transaksi',
    'contentTitle' => 'Edit data_transaksi'
])

@push('css')
<link rel="stylesheet" type="text/css" href="{{ asset('plugins/summernote') }}/summernote-bs4.min.css">
@endpush

@section('content')
<div class="">    
    <div class="card">
        <div class="card-header">
            <a href="{{ route('admin.data_transaksi.index') }}" class="btn btn-success btn-sm">Kembali</a>
        </div>
        <div class="card-body">
        <form method="POST" enctype="multipart/form-data" action="{{ route('admin.data_transaksi.update',$data_transaksi->id) }}">
            @csrf
            @method('PATCH')
            <div class="form-group">
                <label for="petugas">petugas</label>
                <input required="" value="{{ $data_transaksi->petugas }}" required="" type="" name="petugas" id="petugas" placeholder="" class="form-control title"> 
            </div>
            <div class="form-group">
                <label for="judul">Judul</label>
                <input required="" value="{{ $data_transaksi->judul }}" required="" type="" name="judul" id="judul" placeholder="" class="form-control title"> 
            </div>
            
            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="tgl">Tanggal</label>
                        <input required="" value="{{ $data_transaksi->tgl }}" type="date" name="tgl" id="tgl" class="form-control">
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="jam">jam</label>
                        <input required="" value="{{ $data_transaksi->jam }}" type="time" name="jam" id="jam" class="form-control">
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="berat">berat</label>
                        <input required="" value="{{ $data_transaksi->berat }}" type="weight" name="berat" id="berat" class="form-control">
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label for="totalberat">total berat</label>
                            <input required="" value="{{ $data_transaksi->totalberat }}" type="weight" name="totalberat" id="totalberat" class="form-control">
                        </div>
                    </div>
                <div class="col-lg-6">
                    <div class="form-group">
                        <label for="harga">harga</label>
                        <input required="" value="{{ $data_transaksi->harga }}" type="price" name="harga" id="harga" class="form-control">
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="form-group">
                    <label for="totalharga">total harga</label>
                    <input required="" value="{{ $data_transaksi->totalharga }}" type="price" name="totalharga" id="totalharga" class="form-control">
                </div>
            </div>
        </div>
            
            <div class="form-group">
                <label for="deskripsi">Deskripsi</label>
                <textarea required="" name="deskripsi" id="deskripsi" class="text-dark form-control summernote">{!! $data_transaksi->deskripsi !!}</textarea>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-sm">UPDATE</button>    
            </div> 
        </div>
        </form>
    </div>
</div>
@stop

@push('js')
<script type="text/javascript" src="{{ asset('plugins/summernote') }}/summernote-bs4.min.js"></script>
<script type="text/javascript">
    $(".summernote").summernote({
        height:500,
        callbacks: {
        // callback for pasting text only (no formatting)
            onPaste: function (e) {
              var bufferText = ((e.originalEvent || e).clipboardData || window.clipboardData).getData('Text');
              e.preventDefault();
              bufferText = bufferText.replace(/\r?\n/g, '<br>');
              document.execCommand('insertHtml', false, bufferText);
            }
        }
    })

    $(".summernote").on("summernote.enter", function(we, e) {
        $(this).summernote("pasteHTML", "<br><br>");
        e.preventDefault();
    });
</script>
@endpush

resources/views/admin/data_transaksi/index.blade.php
@extends('layouts.backend.app',[
'title' => 'Manage Data Transaksi',
'contentTitle' => 'Manage Data Transaksi',
])
@push('css')
<!-- DataTables -->
<link rel="stylesheet" href="{{ asset('templates/backend/AdminLTE-3.0.1') }}/plugins/datatables-bs4/css/dataTables.bootstrap4.css">
@endpush
@section('content')
<x-alert></x-alert>
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header">
        <a href="{{ route('admin.data_transaksi.create') }}" class="btn btn-primary btn-sm">Tambah Data</a>
      </div>
      <div class="card-body table-responsive">
        <table id="dataTable1" class="table table-bordered table-hover text-center">
          <thead class="bg-info">
            <tr>
              <th>No</th>
              <th>petugas</th>
              <th>Judul</th>
              <th>Tgl Upload</th>
              <th>jam</th>
              <th>berat</th>
              <th>total berat</th>
              <th>harga</th>
              <th>total harga</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            @php
            $no=1;
            @endphp

            @foreach($data_transaksi as $agd)
            <tr>
              <td>{{ $no++ }}</td>
              <td>{{ $agd->petugas }}</td>
              <td>{{ $agd->judul }}</td>
              <td>{{ \Carbon\Carbon::parse($agd->tgl)->format('d-m-Y') }}</td>
              <td>{{ $agd->jam }}</td>
              <td>{{ $agd->berat }}</td>
              <td>{{ $agd->totalberat }}</td>
              <td>Rp.{{number_format( $agd->harga, 0,'','.') }}</td>
              <td>Rp.{{ number_format($agd->totalharga, 0,'','.') }}</td>

              <td>
                <div class="row ml-2">
                  <a href="{{ route('admin.data_transaksi.edit',$agd->id) }}" class="btn btn-primary btn-sm"><i class="fas fa-edit fa-fw"></i></a>

                  <form method="POST" action="{{ route('admin.data_transaksi.destroy',$agd->id) }}">
                    @csrf
                    @method('DELETE')
                    <button onclick="return confirm('Yakin hapus ?')" type="submit" class="btn btn-danger btn-sm ml-2"><i class="fas fa-trash fa-fw"></i></button>
                  </form>
                </div>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
@stop
@push('js')
<!-- DataTables -->
<script src="{{ asset('templates/backend/AdminLTE-3.0.1') }}/plugins/datatables/jquery.dataTables.js"></script>
<script src="{{ asset('templates/backend/AdminLTE-3.0.1') }}/plugins/datatables-bs4/js/dataTables.bootstrap4.js"></script>
<script>
  $(function() {
    $("#dataTable1").DataTable();
  });
</script>
@endpush